services:
  frigate-echo:
    image: tboyk/frigate-echo:latest
    restart: unless-stopped
    container_name: frigate-echo
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /usr/local/frigate-echo:/echo/config
      - /usr/local/frigate/exports:/mnt/frigate_exports
      - /usr/local/syncthing:/mnt/echo_storage